[package]
name        = "nixv"
version     = "0.0.1"
edition     = "2018"

authors     = ["Will <will@glozer.net>"]
description = "Unix version information"
license     = "Apache-2.0"
readme      = "README.md"
repository  = "https://github.com/wg/nixv"

[dependencies]
libc = "0.2.64"
